function Result = CropVolumeTest(VolumeSize, nSlices, CropX, CropY, CropZ, GPU_Device)

reset(gpuDevice(GPU_Device+1));

InputVolume = ones(VolumeSize,VolumeSize,nSlices);

CroppedVolume = mexCropVolume(...
    single(InputVolume), ...
    int32(size(InputVolume)), ...
    int32(CropX), ...
    int32(CropY), ...
    int32(CropZ), ...
    int32(GPU_Device));

GT_CroppedVolume = InputVolume(CropX+1:end-CropX, CropY+1:end-CropY, CropZ+1:end-CropZ);

Result = isequal(GT_CroppedVolume, CroppedVolume);