addpath('C:\GitRepositories\MultiGPUGridder\bin\Debug')

InputVolume = ones(300,300,2);

PaddingX = 20;
PaddingY = 100;
PaddingZ = 1;
GPU_Device = 0;

PaddedVolume = mexPadVolume(...
    single(InputVolume), ...
    int32(size(InputVolume)), ...
    int32(PaddingX), ...
    int32(PaddingY), ...
    int32(PaddingZ), ...
    int32(GPU_Device));

imagesc(PaddedVolume(:,:,2))